### ISSUE TITLE
how to update widget message

### ISSUE THREAD

**Issue by rijink7** [DavidStrausz/cordova-plugin-today-widget#5]
thanks @DavidStrausz for this plugin, it was really helpful.i have a doubt, how to update the messages  in widget screen ?can you send some demo codes.
excuse my bad english

**Comment by DavidStrausz** [comment]
@rijink7 Thanks for opening an issue. I'm not sure I correctly understand what you mean by "how to update the messages in widget screen"?

**Comment by rijink7** [comment]
@DavidStrausz  i want to update some text in the today-widget display on daily basis, is there a way to do so ?

**Comment by DavidStrausz** [comment]
Of course there is, but it has nothing to do with this plugin - which is why I am going to close this issue for now. You will have to implement it using swift/obj-c.
