### ISSUE TITLE
Info.plist is missing

### ISSUE THREAD

**Issue by VanHoutte** [DavidStrausz/cordova-plugin-today-widget#6]
Hi

First of all thanks for the plugin, it's a great help but I do have an issue with the plugin. When my widget is added to my iOS project, the widget itself has no info.plist but it is included in the folder of the widget. I have no idea why the info.plist cannot be found. 

Is it possible to add an example project? It's that I'm not 100% sure how to setup the Widget.entitlements and the Widget-Info.plist. 

Thanks in advance!

**Comment by Gurrt** [comment]
Hi @VanHoutte I'm by no means an expert in using this plugin. But what's the actual error you're getting? I might be able to help a little.

**Comment by VanHoutte** [comment]
> Hi @VanHoutte I'm by no means an expert in using this plugin. But what's the actual error you're getting? I might be able to help a little.

Hi, thanks for the reply! I was able to fix it, I renamed my widget to BarcodeWidget and it was looking for BarcodeWidget-Info.plist. I was able to get it working properly.

**Comment by Gurrt** [comment]
👍
