### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by l3ender** [DavidStrausz/cordova-plugin-today-widget#7]
Can this plugin be published to npm, so we can have easier dependency management (and versioning)?

Also, will the repo owner(s) accept pull requests? I've been using the widget and have come across a few use cases where the plugin can be expanded.

Thanks!

**Comment by l3ender** [comment]
@DavidStrausz @kimalec @RomanovX Is this repo still maintained? If not, would you consider adding others to help support it?

**Comment by DavidStrausz** [comment]
Thanks for opening an issue. 
I currently do not really have the time to invest much into this plugin but usually it should not require much maintenance. Of course you can always submit PRs if there's something you think that's missing, I'll try to review and merge them in time.
Will look into publishing it on npm if this helps your workflow :)
